image: registry.gitlab.com/eighthave/ci-image-git-buildpackage:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -a ../*.deb public/
    - ls public > public/index.html
  artifacts:
    paths:
      - public
