image: registry.gitlab.com/eighthave/ci-image-git-buildpackage:latest

pages:
  stage: deploy
  script:
    - pwd
    - ls -la ..
    - apt-get -y install aptly
    - aptly repo create autobuilt || true
    # could be a sourceful archive if we had the .orig.tar.gz always in the
    # .changes -- withou that, we can't build a source archive anyway, and i'm
    # not sure we should (the git history is the source here)
    # # introducing new distribution "autobuilt"; "experimental" might be just as good.
    # - aptly repo include --accept-unsigned --ignore-signatures --repo autobuilt ../*.changes
    - aptly repo add autobuilt ../*.deb
    - aptly publish repo --skip-signing --distribution autobuilt --architectures "any amd64" autobuilt || aptly publish update --skip-signing --architectures "any amd64" autobuilt
    - rm -rf public
    - cp -a .aptly/public public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - .aptly.conf
      - .aptly/
